spring:
  application:
    name: '${APP_NAME:weshopify-authentication-service}'
  data:
    redis:
      host: '${REDIS_SERVER_HOST:cache.weshopifys.shop}'
      port: '${REDIS_SERVER_PORT:80}'
      password: '${REDIS_SERVER_PASSWORD:Redis123$}'


server:
  port: '${AUTHN_SERVICE_PORT:5022}'

weshopify-platform:
  scim2:
    usersUri: https://${WSO2_SERVER_HOST_NAME:iam.weshopifys.shop}/scim2/Users/
  oauth2:
    uri: https://${WSO2_SERVER_HOST_NAME:iam.weshopifys.shop}/oauth2/token
    logoutUri: https://${WSO2_SERVER_HOST_NAME:iam.weshopifys.shop}/oauth2/revoke
    userInfoUri: https://${WSO2_SERVER_HOST_NAME:iam.weshopifys.shop}/oauth2/userinfo?schema=
    grant_type: ${GRANT_TYPE:password}
    scope: ${SCOPE:openid}
    clientId: ${CLIENT_ID:YxIlY5MY9xmA8edTw9VWyHrsR8Ya}
    clientSecret: ${CLIENT_SECRET:VJdtfbIj4ZfX8DrlFPCwCByEVpsa}