spring:
  application:
    name: weshopify-category-service
  datasource:
    url: 'jdbc:${CATEGORIES_DB_TYPE:mysql}://${CATEGORIES_DB_HOST:localhost}:${CATEGORIES_DB_PORT:3306}/${CATEGORIES_DB_SCHEMA:weshopify-category}'
    username: '${CATEGORIES_DB_USER:root}'
    password: '${CATEGORIES_DB_PASSWORD:test}'
  jpa:
    hibernate:
      ddl-auto: '${CATEGORIES_DB_DDL_AUTO:update}'


  data:
    redis:
      host: '${REDIS_SERVER_HOST:cache.weshopifys.shop}'
      port: '${REDIS_SERVER_PORT:80}'
      password: '${REDIS_SERVER_PASSWORD:Redis123$}'

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka/
  instance:
    hostname: ${SERVICE_REGISTRY_HOST:localhost}

axon:
  axonserver:
    servers: ${AXON_SERVER_HOST:localhost}:${AXON_SERVER_PORT:8024}


server:
  port: '${CATEGORIES_SERVICE_PORT:5016}'
